apiVersion: v1
kind: Service
metadata:
  name: synterix-central
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: synterix-central
  ports:
    - port: {{ .Values.centralGateway.port }}
      targetPort: {{ .Values.centralGateway.port }}