# Global values
global:
  namespace: synterix
  secret:
    name: synterix-secret
    data: c2VjcmV0  # base64 encoded "secret"

# ServiceAccount configuration
serviceAccount:
  name: synterix-central-account

# RBAC configuration
rbac:
  bindingName: synterix-central-account-binding

# Central Gateway configuration
centralGateway:
  image: sebertes/synterix-central-gateway
  tag: master
  port: 7089
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Kube Proxy configuration
kubeProxy:
  image: sebertes/synterix-kube-proxy
  tag: master
  port: 7014
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Central Admin configuration
centralAdmin:
  image: sebertes/synterix-central-admin
  tag: master
  port: 7088
  dbPath: "/synterix/synterix.db"
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  host: "your-domain.com"
  path: "/synterix/(.*)"
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/client-body-buffer-size: 20m
    nginx.ingress.kubernetes.io/keepalive: "32"
    nginx.ingress.kubernetes.io/limit-connections: "65535"
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 20m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 10s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600s
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-http2: "true"