{{- if eq (first .Values.namespaces) "*" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synterix-edge.fullname" . }}-account
  namespace: synterix-edge
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synterix-edge.fullname" . }}-account
  namespace: {{ first .Values.namespaces }}
{{- end }}