name: Release Synterix Central Helm Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Force Chart Changes
        run: |
          sed -i "s/^version: .*/version: ${{ github.event.inputs.version }}/" synterix-central/Chart.yaml
          date > synterix-central/.chart-releaser-force

      - name: Package Chart
        run: |
          mkdir -p packages
          helm package synterix-central/ -d packages/

      - name: Run Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          charts_dir: packages
          pages_branch: gh-pages
          skip_existing: false