name: Release Synterix Edge Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'synterix-edge/**'
      - '.github/workflows/release-edge.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Run Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          charts_dir: synterix-edge
          chart_repo_url: https://github.com/${{ github.repository }}/releases/download
          pages_branch: gh-pages
          push: true